# Generated by Django 3.2.4 on 2021-07-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_n', models.CharField(max_length=70)),
                ('number_of', models.IntegerField()),
            ],
        ),
    ]
